### ISSUE TITLE
Park and Ride updates

### ISSUE THREAD

**Issue by ed-g** [ODOT-PTS/TNAST_MAVEN#14]
Update park & ride data. Phil can provide the most current P&R data set. (Phil, Joel can point you to this, we want to use the “public” subset of park & rides for the TNA tool). As of today there is no longer a process in place for P&R dataset updates at ODOT.

**Comment by PPaulsonOregonDOT** [comment]
[ODOT_P_R_List.zip](https://github.com/pouyalireza/TNAST_MAVEN/files/1232845/ODOT_P_R_List.zip)
 
That's the Park and Ride List from the public ODOT FTP site.

**Comment by ed-g** [comment]
@srinivas13794 yes please document what you changed and upload the CSV here. Ok if its still under development.

**Comment by ed-g** [comment]
@srinivas13794 just a reminder to please upload your version of the PNR data.

**Comment by ed-g** [comment]
@srinivas13794 any update on this?

**Comment by srinivas13794** [comment]
Sorry for the delay I will upload this by the end of the today.

**Comment by srinivas13794** [comment]
@ed-g I will send out an email with a file containing the new park and ride data that is in the right format for the admin interface.However, this file is still missing some data. @PPaulsonOregonDOT  Would you be able to get data for the rows highlighted? I will also attach a file that is a reference for future park and ride data updates (**This can be got through the admin interface under notes**).

**Comment by srinivas13794** [comment]
@ed-g @PPaulsonOregonDOT  here are the files 
[p_r.zip](https://github.com/pouyalireza/TNAST_MAVEN/files/1330658/p_r.zip)

**Comment by ed-g** [comment]
It looks like we still need to review the spreadsheet. Look at it and then see how much work to fill in gaps.
