### ISSUE TITLE
Time of day reports.

### ISSUE THREAD

**Issue by ed-g** [ODOT-PTS/TNAST_MAVEN#22]
Reporting with a time of day focus, to allow better understanding a timing variations in service availability/frequency
Recommend approach(es)

**Comment by ed-g** [comment]
Categorize as more complex task.

**Comment by PPaulsonOregonDOT** [comment]
I think that this can be implemented outside of the TNA tool, using the stops export and Tableau. If there is additional required functionality, I think that this visualization could serve as a template:
https://public.tableau.com/profile/phil2727#!/vizhome/ServiceMetricsStory/ServiceMetricsData

**Comment by PPaulsonOregonDOT** [comment]
Do we want to pursue this functionality solely within the tool itself, or is it doable to integrate outside GIS/Data visualization software to accomplish this task? One observation I do have about this data is that there are a lot of null time values in the shapefile exports, which leaves holes in the data. I suspect this is an artifact of the GTFS data that the tool ingests, but more clarity on exactly how this data is created would be appreciated.

**Comment by ed-g** [comment]
@PPaulsonOregonDOT 

I'm only guessing about the output shapefile -- can you point to an example?

It could be that stop_times has a null arrival or departure time for the stop associated with a  shape_dist_travelled.

There are a number of ways to deal with that, the simplest is linear interpolation with distance, from the two nearest stop_times.txt entries containing arrival or departure times.

**Comment by ODOT-RPTD-mb** [comment]
After talking to TPAU staff, they would like to be able to select a geo area, a date, and a time range, and get as output a list of stops (name/id/lat-long) within the geo area each with an associated transit visit count for each agency that visits the stop in the specified date/time-range.

Various urban areas 50k+ will be their initial geo area focus.

**Comment by pouyalireza** [comment]
@ODOT-RPTD-mb  Would this be a separate report or a part of an existing report? Adding a time interval filter to the stops report would be a possibility to consider.

**Comment by PPaulsonOregonDOT** [comment]
@ed-g I apologize that this took so long, but I've attached a .zip file of the merged data export from all of the agencies from the May database.
[stops_shape_011536.zip](https://github.com/pouyalireza/TNAST_MAVEN/files/1278761/stops_shape_011536.zip)

**Comment by ed-g** [comment]
@PPaulsonOregonDOT great thank you! I'll take a look this week.

**Comment by PPaulsonOregonDOT** [comment]
@ed-g I think the linear interpolation method will work for our purposes, and there has been some substantial work done in that realm by Melinda Morang here: http://transit.melindamorang.com/overview_InterpolateBlankStopTimes.html. The only potential issue with this method being accurate is that not all gtfs files contain shapes.txt, because it's not a required file, and using straight line distance could end up with some really awful estimates.

**Comment by ed-g** [comment]
@PPaulsonOregonDOT I'm not enough of a mathematician to make a suggestion when no shape data is available.

It seems like the options are:

* agencies without shapes can not be included in the report
* agencies without shapes need manually updated stop times. An analyst looks at a map and makes an educated guess as to arrival times for the missing stops. Or calls the agency. Or tracks down realtime arrival information or published schedules which might say more than the GTFS.
* if your report includes agencies without shapes, we make a guess based on straight-line routes and let you know that your report could be wildly inaccurate.

What are the consequences for each of these, and costs for implementation?

**Comment by PPaulsonOregonDOT** [comment]
@ed-g I don't think the "no shape availible" is a problem for any agencies in Oregon, as those have a pretty stringent QA/GC process. However, if we ever want to expand the usage of the tool beyond the state of Oregon, we should probably include a warning about this at some point in the process, so that states can implement option 2 or 3 on this list..

**Comment by PPaulsonOregonDOT** [comment]
@srinivas13794 @BenFields724 @srinivas13794. I checked out the stops report with the time limitations for Baker County, and I think that that report will give us a lot of the information we want. The remaining issues is the blank rows in stop_times.txt. Is there a way we can programatically deal with those that doesn't require modification of the GTFS feeds before they get fed into the tool?

**Comment by ed-g** [comment]
Srinivas: linear interpolation may be OK.

**Comment by ODOT-RPTD-mb** [comment]
Stepped through stops summary report for Portland Metro Urban area, for agency = TriMet, with default time range 0-23:59, did not see any zero visit stops. I assume that this means some kind of linear interpolation is in place? If so we need some kind of brief user focused documentation of how we are handling this.

http://tna.trilliumtransit.com:8080/TNAtoolAPI-Webapp/stopreport.html?&areaid=71317&type=3&x=0.25&n=jAr&dbindex=10&popYear=2010&geotype=-1&geoid=null&stime=0:00&etime=23:59&nav=stateS-urbanS&rc=-1

**Comment by ed-g** [comment]
4 hours investigation.

My recommendation is:
* a simple fix that allows valid results for oregon gtfs data. 8 hour-12 hours.
* clear error message if you attempt to run this report on any GTFS without shapes or where interpolation is fraught for any other reason. 2 hours.
  * along with thorough documentation of options for extending this to GTFS without shapes. 3 hours.
