### ISSUE TITLE
automatically symlink xml config files during build process

### ISSUE THREAD

**Issue by ed-g** [ODOT-PTS/TNAST_MAVEN#70]
Quite a hack, but better than no solution.

https://github.com/pouyalireza/TNAST_MAVEN/issues/69#issuecomment-339812259

**Comment by ed-g** [comment]
Note this means if you add or change settings for a database you must **rebuild and reinstall** the network analysis for transit application.

**Comment by ed-g** [comment]
Design work is making sure that the auto-symlinks don't destroy any important files if the build variables are set to unexpected variables. Easiest way to do that is hard code a path, intentionally reducing the flexibility. This is supposed to be a stop-gap anyhow.

2-3 hours.

**Comment by irees** [comment]
I made improvements to the configuration management and the per-database .xml files are no longer needed.
