### ISSUE TITLE
GTFS update should not fail due to http connection reset

### ISSUE THREAD

**Issue by ed-g** [ODOT-PTS/TNAST_MAVEN#74]
> I tried to update RVTD GTFS in the September 2017  with an accurate calendar.txt file over the extended weekend. From what I can tell, it looks like my machine updated/reset the connection at some point, which closed the update process before it was finished, which may have caused some corruption in that database.

**Comment by ed-g** [comment]
Find a way to reproduce on a testing database.

**Comment by PPaulsonOregonDOT** [comment]
We're at about the 3 month mark for this database, so I think it is probably appropriate to start looking towards providing a November version of the database, which will solve all the problems with the RVTD database, and also allow us to pull Valley Retriever fully out of service. Even with the deprecated status, it's still effecting the Key Transit Hub report, and in talking with @ODOT-RPTD-mb, the consensus was that it should be permanently pulled, until we hear that the route is back in operation. I'm going to start looking at the gtfs feeds to see if there are any issues that need to be fixed before we upload the new batch, with a focus on those that are not produced by Trillium, with a target build start time of end of business on 11/16.

**Comment by PPaulsonOregonDOT** [comment]
The September 2017 appears to be broken and hung up on updating, and I can't create a new instance of the database until it is activated. I have discovered a seemingly random approach to the use of the calendar.txt vs. calendar_dates.txt vs. feed_info.txt, to set the end date for a feed  for some of the independent GTFS producers that may be causing the unwanted behavior I was trying to fix by updating this GTFS feed in the database.

**Comment by ODOT-RPTD-mb** [comment]
New GTFS snapshot moved to #78, this issue remains bug fix.
