### ISSUE TITLE
Reorganize db to support stable db to match stable app instance

### ISSUE THREAD

**Issue by ODOT-RPTD-mb** [ODOT-PTS/TNAST_MAVEN#77]
Currently both stable and development tnast point to same db, so db issues impact both instances.

Modify db setup to make stable app db independent, while still supporting effective debugging.

\ | production code | development code
-- | -- | --
production data | production | staging
testing data | testing | developent

**Comment by irees** [comment]
containerized staging instance is up using new setup; containerized production instance will be setup at next stable release.
