### ISSUE TITLE
Missing Geographies in April 2018 Database

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [ODOT-PTS/TNAST_MAVEN#91]
I noted that the Key Transit Hub Report shows 0 for the county and census place count, which doesn't make any sense. 

http://tna.trilliumtransit.com:8090/TNAtoolAPI-Webapp/KeyHubSreport.html?&x1=0.08&x2=0.25&x3=2&n=cbs&dbindex=11&popYear=2010
This behavior is carried over into the geographic reports, which show 0 agencies, routes, etc
**Counties**
http://tna.trilliumtransit.com:8090/TNAtoolAPI-Webapp/GeoCountiesReport.html?&dbindex=11&popYear=2010#
**Census Place**
http://tna.trilliumtransit.com:8090/TNAtoolAPI-Webapp/GeoPlacesReport.html?&dbindex=11&popYear=2010

When I revert to the Sept 2017 database, these reports show data that makes sense.

**Comment by ODOT-RPTD-mb** [comment]
**Stops**
http://tna.trilliumtransit.com:8090/TNAtoolAPI-Webapp/stopreport.html?&agency=101&n=ces&x=0.25&dbindex=11&popYear=2010&geotype=-1&geoid=null&areaid=null&type=null&route=null&nav=stateS-agencyS&rc=-1&stime=0:00&etime=23:59

**Comment by irees** [comment]
It looks like this issue and #92 are related to an incorrect copy of one of the census geography tables. Checking to see exactly what is different.

**Comment by irees** [comment]
The stops weren't geocoded correctly - fixing.

**Comment by irees** [comment]
Will be resolved in #97

**Comment by irees** [comment]
Resolved in #97
