### ISSUE TITLE
Transit Agency Extended Report

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [ODOT-PTS/TNAST_MAVEN#93]
The April 2018 database version of the extended agency report for trimet appears to be suffering from a similar issue to #90, but complicated by the fact that I'm not 100% sure which version of the feeds went into the database, so I'm not clear if this might be a calendar_dates.txt problem in the feed itself, or if it's the an error in the tool or database:
April 2018 for a set of dates that service should operate according to start and end dates:
http://tna.trilliumtransit.com:8090/TNAtoolAPI-Webapp/AgenXReport.html?&agency=TRIMET&x=0.25&l=2&n=cfscgschs&dbindex=11&popYear=2010&areaid=null&type=0&username=admin&geotype=-1&geoid=null&nav=stateS-agencyS 

**Compare to the Sept 2017 Version under same circumstances:**
http://tna.trilliumtransit.com:8090/TNAtoolAPI-Webapp/AgenXReport.html?&agency=TRIMET&x=0.25&l=2&n=kgrkhrkir&dbindex=10&popYear=2010&areaid=null&type=0&username=admin&geotype=-1&geoid=null&nav=stateS-agencyS

**Comment by irees** [comment]
@PPaulsonOregonDOT Can you see if this is resolved in the most recent build?

http://tna.trilliumtransit.com:8090/TNAtoolAPI-Webapp/AgenXReport.html?&agency=TRIMET&x=0.25&l=2&n=cfscgschs&dbindex=11&popYear=2010&areaid=null&type=0&username=admin&geotype=-1&geoid=null&nav=stateS-agencyS

**Comment by irees** [comment]
Please feel free to re-open the issue if the updated build is not correct.
